### Product Index
GET http://localhost:3000/products/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDc5OTY3NzF9.isc8OnM0SvhOVrqIOAJnltm_GcuDYtFps8g_qFrvpwk"

### Product Show
GET http://localhost:3000/products/1

### Product Create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Barbie clothes",
  "price": 67.99 ,
  "description": "Comes with an extra bonnet.",
  "supplier_id": "2"
}

### Product Update
PATCH http://localhost:3000/products/7
Content-Type: application/json

{
  "name": "Troll with purple belly button"
}


### Product Destroy
DELETE http://localhost:3000/products/5

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name 1",
  "email": "test1@test.com",
  "password": "password1",
  "password_confirmation": "password1"
}
  

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "password1"
}