### Product Index
GET http://localhost:3000/products/

### Product Show
GET http://localhost:3000/products/4

### Product Create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Strawberry Shortcake Doll",
  "price": 67.99 ,
  "image_url": "n/a",
  "description": "Comes with an extra bonnet."
}

### Product Update
PATCH http://localhost:3000/products/7
Content-Type: application/json

{
  "name": "Troll with purple belly button"
}


### Product Destroy
DELETE http://localhost:3000/products/5
  