Product.create!([
  {name: "Cosmic Love Silly Putty", price: 5, image_url: "https://cdn.commercev3.net/cdn.teachersource.com/images/popup/sl510.jpg", description: "This silly putty is extra fun with 3 colors and gobs of glitter. Mix together for a slimy cosmic swirl!", quantity: 9},
  {name: "Yo-yo", price: 9, image_url: "https://i5.walmartimages.com/asr/d6153b5a-1140-4c9e-b27f-2b2ae6ab95e9_1.2aa1d3b764f24cf261dba534edf89075.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", description: "Yo-yo master certified, be the coolest kid in the world, get this yo-yo. ", quantity: 6},
  {name: "glitter slinky", price: 6, image_url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F244179611021823354%2F&psig=AOvVaw158k1um1T0qaRcPROfTeCs&ust=1647273975706000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCOichfa7w_YCFQAAAAAdAAAAABAF", description: "It's beautiful.", quantity: 3},
  {name: "Strawberry Shortcake Doll", price: 67, image_url: "n/a", description: "Comes with an extra bonnet.", quantity: 2},
  {name: "Chicago Puzzle", price: 18, image_url: "https://render.fineartamerica.com/images/rendered/default/flat/puzzle/images-medium-5/chicago-joe-daniel-price.jpg?&targetx=-106&targety=0&imagewidth=1213&imageheight=750&modelwidth=1000&modelheight=750&backgroundcolor=252F52&orientation=0&producttype=puzzle-18-24&brightness=166&v=6", description: "5000 pieces, beware! There is definitely at least one missing piece. ", quantity: 4},
  {name: "Troll with purple belly button", price: 19, image_url: "https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1120w,f_auto,q_auto:best/newscms/2018_02/1309269/polly-pocket-magical-mansion.jpg", description: "You don't have this one yet. Super rare. You can recreate Dynasty with this one!", quantity: 4},
  {name: "Unicorn Pop-it Figit", price: 7, image_url: "https://m.media-amazon.com/images/I/81LF+rg2pHL._AC_SL1500_.jpg", description: "This figit pop-it is super beautiful and perfect in every single way. This unicorn comes with 2 awesome tiny pop-it keychains. ", quantity: 8}
])
